name: Nightly Release

on:
  schedule:
    - cron: '0 0 * * *' # 
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: .NET SDK Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Ersetzen Sie dies mit Ihrer benötigten .NET SDK Version

      - name: NuGet Pakete Restore
        run: dotnet restore

      - name: Build WPF Application
        run: dotnet build --configuration Release

      - name: Get Release Date
        id: get_date
        run: echo "::set-output name=date::$(Get-Date -Format 'yyyyMMdd')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-${{ steps.get_date.outputs.date }}
          release_name: Nightly Release ${{ steps.get_date.outputs.date }}
          body: |
            Diese Release beinhaltet die nächtliche Version der WPF Desktop Anwendung.
          draft: false
          prerelease: true

      - name: Upload .exe
        id: upload-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/Release/TraceViewer.exe
          asset_name: TraceViewer-nightly-${{ steps.get_date.outputs.date }}.exe
          asset_content_type: application/octet-stream
